### PR TITLE
go.mod: initial commit, switch to packet package

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

Prerequisite for https://github.com/gokrazy/gokrazy/pull/109.

/cc @stapelberg

### CODE REVIEW

**Comment by stapelberg** [comment]
This breaks the https://github.com/rtr7/router7 tests for me (with a replace directive in go.mod):

```
[…]
=== RUN   TestDHCPv4
dnsmasq log line: dnsmasq[1155196]: started, version 2.86 cachesize 150
dnsmasq log line: dnsmasq[1155196]: compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC loop-detect inotify dumpfile
dnsmasq log line: dnsmasq-dhcp[1155196]: DHCP, IP range 192.168.23.2 -- 192.168.23.10, lease time 1h
dnsmasq log line: dnsmasq-dhcp[1155196]: DHCPv6, IP range ::1 -- ::10, lease time 1d, template for veth0b
dnsmasq log line: dnsmasq-dhcp[1155196]: DHCP, sockets bound exclusively to interface veth0b
dnsmasq log line: dnsmasq[1155196]: reading /etc/resolv.conf
dnsmasq log line: dnsmasq[1155196]: using nameserver 127.0.0.53#53
dnsmasq log line: dnsmasq[1155196]: read /etc/hosts - 7 addresses
    dhcpv4_test.go:115: DHCP: invalid argument
--- FAIL: TestDHCPv4 (0.03s)
[…]
```

**Comment by mdlayher** [comment]
@stapelberg yeah I think we have the same problem there, it's hard-coding raw.Addr and passing those to opaque net.Addr APIs. We'll have to make the transition all at once.

Otherwise I can do some type assertions here on the net.PacketConn and support both address types for now for the transition?

I had planned to send the router7 PR once this was landed.

**Comment by stapelberg** [comment]
Adding type assertions to make the transition a little easier sounds good to me

**Comment by mdlayher** [comment]
@stapelberg okay! I think this will work. I am trying to work on router7 now too.

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Yep, tests still work! Thanks!

**Pull request merged**
